### ISSUE TITLE
团队称号候选

### ISSUE THREAD

**Issue by mamboer** [o2team/o2team.github.io#1]
### 小马
* 英文：O2
* 中文：凹凸
* 域名：o2team.com
* github:o2team
* 寓意：1.化学式O2，氧气，赖以生存的东西；2.O2 = OO = Object Oriented（面向对象），软件开发的主流思想；3.O2 = OO = Open Obejct，开源 对象，软件开发领域关键词。
* 口号：?

**Comment by yevolcn** [comment]
中文：叁零（三零）
英文：30Team
域名：30team.com
github：30team
寓意：1.目前的人数，一个纪念。2.纯数字，略文艺，略比格，便于记忆和传播。3.可以暗指团队年龄，大多处于奔三的年级，而立之年。

**Comment by mamboer** [comment]
### 老黄
* 英文：mif
* 中文：蜜蜂、米饭、米粉
* 域名：mif.im、mifun.co、mifun.org
* Github: mifun
* 寓意：？在想ing
* 口号：Make It Fun!

**Comment by huangliyn** [comment]
英文：7. （geekpoint）
中文：奇点
域名：7.jdc.com
github:7.team geekpintteam
寓意：奇思妙想，点石成金。化奇思妙想（设计想法）为神奇
口号：奇思妙想，点石成金。

**Comment by cnt1992** [comment]
## 伟大的天哥
- 英文：jit
- 中文：就是干
- 域名：jit.com
- Github: jit
- 寓意：不要犹豫，不要后退，碰到问题就是干
- 口号： Just Do IT

**Comment by panxinwu** [comment]
## 瘦子潘
* 英文：O2
* 中文：鹰眼Team
* 别名： 京鹰
* 域名：o2team.com
* github:o2team\ JdEagleEye
* 寓意：O2象征鹰的两只眼睛\鹰眼犀利的眼神可以看透一切猎物（Bug/需求点/前端的发展方向）所在\鹰从古至今都是一种正面帅气的形象。传说：鹰是天的神鸟使者。
* 图片：![Image of EagleEye](http://news.cnhubei.com/news/todaynews/hw/whwbszb/201006/W020100629433006001895.jpg)

**Comment by mamboer** [comment]
## feeling

* 英文：seeking ，简写 SK
* 中文：？
* 域名：seeking.im
* Github: coolsk (Cool SK)
* 寓意：表现团队的愿景，对技术的探索，对人才的渴望
