### ISSUE TITLE
V3 - 微信登录优化

### ISSUE THREAD

**Issue by mamboer** [o2team/o2team.github.io#15]
是否可以避免跳新窗口，改用「浮层套一个iframe」的交互？

新窗口可能会被拦截

![image](https://cloud.githubusercontent.com/assets/85879/21494000/5f2d8496-cc49-11e6-8dc1-46db9c8a6f99.png)

**Comment by Calvin92** [comment]
这个真的会被拦截么？   我查了下资料   说是只有脚本自动执行的才有可能被拦截哦    被用户click产生的执行脚本是不会拦截的~~

**Comment by chuyik** [comment]
建议弹出新窗口，这个是第三方登录通用的做法。
