### ISSUE TITLE
error loacl not found hexo in '路径'

### ISSUE THREAD

**Issue by labike** [o2team/o2team.github.io#20]
running hexo s --watch:
    error local not found hexo in '....'

**Comment by mamboer** [comment]
Provide more info about your node env pls.

**Comment by labike** [comment]
ok,thanks! please screen my error image:
[error1](http://oo8hp4ueg.bkt.clouddn.com/2017-04-11_150459.png)
[error2](http://oo8hp4ueg.bkt.clouddn.com/2017-04-11_150636.png)

**Comment by chuyik** [comment]
@labike It looks like the dependencies are not installed correctly, you may want to remove the node_modules/ directory and reinstall it.

**Comment by mamboer** [comment]
@labike You should install python firstly, 
https://www.python.org/

**Comment by labike** [comment]
before install o2,my system the python version 3.6
