### ISSUE TITLE
rss-link is broken

### ISSUE THREAD

**Issue by WoHal** [o2team/o2team.github.io#21]
https://aotu.io/atom.xml

**Comment by mamboer** [comment]
Fixed, thanks.

**Comment by mamboer** [comment]
For rss users, we recommend using  https://feedly.com/ for better reading experience.

**Comment by cnt1992** [comment]
![image](https://cloud.githubusercontent.com/assets/3118988/25228364/c5eec294-25fe-11e7-9015-050ad30e97e3.png)
@mamboer is it `messy code`?

**Comment by mamboer** [comment]
@cnt1992 检查了一番，貌似是feedly的问题~ 自动抓取description不支持中文
