### ISSUE TITLE
申请加入凹凸实验室

### ISSUE THREAD

**Issue by DaHeaths** [o2team/o2team.github.io#22]
”co-editor”
我希望可以加入凹凸实验室，来共同编辑技术文章。谢谢！
名字：Daheaths
出生日期：1997.08
邮箱：daheaths@gmail.com
个人喜好：喜欢钻研新技术，热爱开发，希望能加入你们凹凸实验室！谢谢

**Comment by mamboer** [comment]
嗨，关于「联合编辑」，我们今年下半年起，「直接加入凹凸实验室」需要已有凹凸实验室成员的推荐（wiki说明已更新）。具体请查看我给你发的邮件。
