### ISSUE TITLE
你好 请问有简历么 :)

### ISSUE THREAD

**Issue by xunuo** [o2team/o2team.github.io#3]
From AliF2E :)

**Comment by chuyik** [comment]
@xunuo 你好，是想投简历吗？可以发到 zhuyiteng#jd.com 哦！:smile: 

<a href="http://aotu.io/" target="_blank">凹凸实验室(o2team.github.io)</a>欢迎你~~

**Comment by xunuo** [comment]
。。。呃 误会了， 您现在在找工作么，想来杭州阿里巴巴么。

**Comment by chuyik** [comment]
@xunuo 哦~这个是我们凹凸实验室的博客 repo，还以为你要发简历呢...
我们也在招人哈，若你感兴趣加入我们，也不妨了解一下喔！ :yum:

**Comment by jangdelong** [comment]
工作地点是在深圳吗？

**Comment by jangdelong** [comment]
不错。菜鸟飘过😄~
