### ISSUE TITLE
RSS feed broken

### ISSUE THREAD

**Issue by chuyik** [o2team/o2team.github.io#7]
`atom.xml` contains some syntax errors, thus the crawler stops working.
Link here: https://aotu.io/atom.xml

**Comment by mamboer** [comment]
Hi,
This a bug of the official plugin [hexo-generator-feed](https://github.com/hexojs/hexo-generator-feed/), referring to this issue https://github.com/hexojs/hexo-generator-feed/issues/42 .

Currently we should avoid using the special chars like '😱' in the post content, just go and fix it.
